@startuml da_consultar_cliente
Title Consultar Cliente
|Empleado|
start
:Ingresar término de búsqueda;
|Sistema|
:Buscar cliente por término de búsqueda;
:Mostrar resultados de búsqueda;
|Empleado|
:Seleccionar cliente para consultar;
:Visualizar detalles del cliente;
|Sistema|
:Obtener información detallada del cliente;
:Mostrar detalles del cliente;
stop
@enduml
