@startuml da_consultar_Categoria
Title Consultar Categoría de Artículos
|Empleado|
start
:Ingresar término de búsqueda;
|Sistema|
:Buscar Categoría de Artículos por término de búsqueda;
:Mostrar resultados de búsqueda;
|Empleado|
:Visualizar datos de la Categoría de Artículos;
stop
@enduml
