@startuml da_Editar_Egreso
Title Editar Egreso
|Empleado|
start
:Seleccionar egreso a editar;
|Sistema|
:Mostrar detalles del egreso;
|Empleado|
:Modificar datos del egreso;
|Sistema|
:Validar nuevos datos del egreso;
if (Detalles válidos?) then (Sí)
    :Guardar cambios en la base de datos;
    |Empleado|
    :Mostrar confirmación de edición;
    stop
else (No)
    |Empleado|
    :Mostrar mensaje de error;
    stop
endif
@enduml
