@startuml da_Editar_Cita
Title Editar Cita
|Empleado|
start
:Seleccionar cita a editar;
|Sistema|
:Mostrar detalles de la cita;
|Empleado|
:Modificar detalles de la cita;
|Sistema|
:Validar nuevos detalles de la cita;
if (Detalles válidos?) then (Sí)
    :Guardar cambios en la base de datos;
    |Empleado|
    :Mostrar confirmación de edición;
    stop
else (No)
    |Empleado|
    :Mostrar mensaje de error;
    stop
endif
@enduml
