@startuml da_editar_articulo
Title Editar articulo
|Empleado|
start
:Seleccionar articulo a actualizar;
:Ingresar nuevos datos del articulo;
|Sistema|
if (Datos válidos?) is (Si) then
:Guardar articulo en la base de datos;
|Empleado|
:Mostrar confirmación de actualización;
stop
else (No)
|Empleado|
:Mostrar mensaje de error;
stop
@enduml
