@startuml da_Editar_Talonario
Title Editar Talonario
|Empleado|
start
:Seleccionar talonario a editar;
|Sistema|
:Mostrar detalles del talonario;
|Empleado|
:Modificar detalles del talonario;
|Sistema|
:Validar nuevos detalles del talonario;
if (Detalles válidos?) then (Sí)
    :Guardar cambios en la base de datos;
    |Empleado|
    :Mostrar confirmación de edición;
    stop
else (No)
    |Empleado|
    :Mostrar mensaje de error;
    stop
endif
@enduml
