@startuml da_editar_vehiculo
Title Editar Vehiculo
|Empleado|
start
:Seleccionar vehiculo a actualizar;
:Ingresar nuevos datos del vehiculo;
|Sistema|
if (Datos válidos?) is (Si) then
:Guardar vehiculo en la base de datos;
|Empleado|
:Mostrar confirmación de actualización;
stop
else (No)
|Empleado|
:Mostrar mensaje de error;
stop
@enduml
