@startuml da_Editar_Presupuesto
Title Editar Presupuesto
|Empleado|
start
:Seleccionar presupuesto a editar;
|Sistema|
:Mostrar detalles del presupuesto;
|Empleado|
:Modificar detalles del presupuesto;
|Sistema|
:Validar nuevos detalles del presupuesto;
if (Detalles válidos?) then (Sí)
    :Guardar cambios en la base de datos;
    |Empleado|
    :Mostrar confirmación de edición;
    stop
else (No)
    |Empleado|
    :Mostrar mensaje de error;
    stop
endif
@enduml
