@startuml da_Registrar_Cita
Title Registrar Cita
|Empleado|
start
:Ingresar detalles de la cita;
:Seleccionar vehículo;
:Seleccionar fecha y hora;
|Sistema|
:Validar detalles de la cita;
if (Detalles válidos?) then (Sí)
    :Guardar cita en la base de datos;
    |Empleado|
    :Mostrar confirmación de registro;
    stop
else (No)
    |Empleado|
    :Mostrar mensaje de error;
    stop
endif
@enduml
