@startuml da_registrar_vehiculo
Title Registrar Vehiculo
|Empleado|
start
:Ingresar datos del vehiculo;
|Sistema|
:Validar datos;

if (Datos válidos?) is (Si) then
:Guardar vehiculo en la base de datos;
|Empleado|
:Mostrar confirmación de registro;
stop
else (No)
|Empleado|
:Mostrar mensaje de error;
stop
