@startuml caso_de_uso_egresos

left to right direction

title Gestión de Egresos

actor Empleado as User

package Sistema {

    USECASE "Registrar Egresos" as UC_Registrar
    USECASE "Editar Egresos" as UC_Editar
    USECASE "Consultar Egresos" as UC_Consultar
    USECASE "Eliminar Egresos" as UC_Eliminar

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar
User --> UC_Eliminar

@enduml