@startuml usuario

left to right direction

title Gestión de Proveedores

actor Usuario as User

package Sistema {

    USECASE "Registrar Proveedores" as UC_Registrar
    USECASE "Editar Proveedores" as UC_Editar
    USECASE "Consultar Proveedores" as UC_Consultar

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar

@enduml