@startuml usuario

left to right direction

title Gestión de Ordenes de Trabajo

actor Usuario as User

package Sistema {

    USECASE "Generar Ordenes de Trabajo" as UC_Registrar
    USECASE "Editar Ordenes de Trabajo" as UC_Editar
    USECASE "Consultar Ordenes de Trabajo" as UC_Consultar
    USECASE "Actualizar Estado" as UC_Editar_Estado

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar
UC_Editar ..> UC_Editar_Estado

@enduml