@startuml CU_Recibo

left to right direction

title Gestión de Recibos de Cobranza

actor Empleado as User

package Sistema {

    USECASE "Registrar Recibos" as UC_Registrar
    USECASE "Editar Recibos" as UC_Editar
    USECASE "Consultar Recibos" as UC_Consultar
    USECASE "Actualizar Estado" as UC_Editar_Estado
    USECASE "Eliminar Detalle" as UC_Eliminar_Detalle

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar
UC_Editar ..> UC_Editar_Estado
UC_Editar ..> UC_Eliminar_Detalle

@enduml