@startuml CU_Talonario

left to right direction

title Gestión de Talonarios

actor Empleado as User

package Sistema {

    USECASE "Crear Talonario" as UC_Registrar
    USECASE "Editar Talonario" as UC_Editar
    USECASE "Consultar Talonario" as UC_Consultar
    USECASE "Actualizar Estado" as UC_Editar_Estado

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar
UC_Editar ..> UC_Editar_Estado

@enduml