@startuml usuario

left to right direction

title Gestión de Citas

actor Usuario as User

package Sistema {

    USECASE "Registrar Citas" as UC_Registrar
    USECASE "Editar Citas" as UC_Editar
    USECASE "Eliminar Citas" as UC_Eliminar
    USECASE "Consultar Citas" as UC_Consultar

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Eliminar
User --> UC_Consultar

@enduml