@startuml usuario

left to right direction

title Gestión de Citas

actor Usuario as User

package Sistema {

    USECASE "Registrar Citas" as UC_Registrar
    USECASE "Editar Citas" as UC_Editar
    USECASE "Consultar Citas" as UC_Consultar
    USECASE "Actualizar Estado" as USE_Actualizar

    UC_Editar ..> USE_Actualizar
}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar

@enduml