@startuml usuario

left to right direction

title Gestión de Inventarios

actor Usuario as User

package Sistema {

    USECASE "Registrar Inventario" as UC_Registrar
    USECASE "Editar Inventario" as UC_Editar
    USECASE "Consultar Inventario" as UC_Consultar
    USECASE "Eliminar Inventario" as UC_Eliminar
    USECASE "Confirmar Inventario" as UC_Confirmar

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar
User --> UC_Eliminar
UC_Editar ..> UC_Confirmar

@enduml