@startuml caso_de_uso_presupuesto

left to right direction

title Gestión de Presupuestos

actor Empleado as User

package Sistema {

    USECASE "Crear Presupuestos" as UC_Registrar
    USECASE "Editar Presupuestos" as UC_Editar
    USECASE "Consultar Presupuestos" as UC_Consultar
    USECASE "Actualizar Estado" as UC_Editar_Estado

}

User --> UC_Registrar
User --> UC_Editar
User --> UC_Consultar
UC_Editar ..> UC_Editar_Estado

@enduml