@startuml CU_Factura

left to right direction

title Gestión de Facturas

actor Empleado as User

package Sistema {

    USECASE "Generar Facturas" as UC_Generar
    USECASE "Actualizar Facturas" as UC_Editar
    USECASE "Consultar Facturas" as UC_Consultar
    USECASE "Actualizar Estado" as UC_Actualizar_Estado

    UC_Editar ..> UC_Actualizar_Estado

}

User --> UC_Generar
User --> UC_Editar
User --> UC_Consultar

@enduml