@startuml CU_Usuario

left to right direction

title Gestión de Usuarios

actor Empleado as User

package Sistema {

    USECASE "Registrar Usuario" as UC_Registrar
    USECASE "Editar Usuario" as UC_Actualizar
    USECASE "Consultar Usuario" as UC_Consultar
    'USECASE "Iniciar Sesión" as UC_IniciarSesion
    'USECASE "Cerrar Sesión" as UC_CerrarSesion

}

User --> UC_Registrar
User --> UC_Actualizar
User --> UC_Consultar
'User --> UC_IniciarSesion
'User --> UC_CerrarSesion

@enduml