@startuml estado-Factura
[*] --> Generado : Registro completado
Generado --> Pendiente : Pendiende de cobro
Pendiente --> Parcial : Cobro parcial
Pendiente --> Anulado : Anular Factura
Pendiente --> Cobrado: Cobrar Factura
Parcial --> Cobrado: Cobrar Factura
Cobrado -->[*]
Anulado -->[*]
@enduml